### ISSUE TITLE
What version to use in build.gradle, 1.8 does not work

### ISSUE THREAD

**Issue by drupalmav** [borax12/MaterialDateRangePicker#50]
1.8 does not work.
compile 'com.borax12.materialdaterangepicker:library:1.8'

What is the right version to use?

**Comment by larrytech7** [comment]
I think 1.7 should be the most recent release that is stable,  at least for me that's what is working. 1.8 may not have been published yet

**Comment by ghost** [comment]
I have the same problem. 1.8 fails to resolve

**Comment by ghost** [comment]
I found out that the 1.8 .jar was not generated, only the .aar file. (As it can be seen in the [bintray.com/borax12](https://bintray.com/borax12/maven/material-datetime-rangepicker/1.8#files/com/borax12/materialdaterangepicker/library/1.8) page)

So, to use this version, you need to add the "@arr" at the end of the version number, like this:
compile 'com.borax12.materialdaterangepicker:library:1.8@aar'

However, even though it's the latest release, it's not as recent as the code in the repo because, for example, it doesn't come with the (Allow rename tabs for localization)  798a1ea commit.

**Comment by benstone042** [comment]
Use this 
compile 'com.borax12.materialdaterangepicker:library:+'

**Comment by deepwritescode** [comment]
Use this in Gradle compile 'com.borax12.materialdaterangepicker:library:1.8@aar'

This library is only available as a binary, This should be changed because the documentation doesn't come with the code.

**Comment by heysupratim** [comment]
@deep7176 @drupalmav @larrytech7 @PIPOKID @benstone042 - I will be updating the next version in a day , till then please use the binary , there was some issue with the jar.
