### ISSUE TITLE
It doesn't work with original wdullaer/MaterialDateTimePicker

### ISSUE THREAD

**Issue by Kamil-Kaminski** [borax12/MaterialDateRangePicker#64]
If I want to use this library (for data ranges), and original library https://github.com/wdullaer/MaterialDateTimePicker (for one date picker) - then my gradle didn't sync, because of some ids conflicts:
```
/myApp/app/build/intermediates/exploded-aar/com.wdullaer/materialdatetimepicker/3.0.0/res/layout-land/mdtp_time_header_label.xml
Error:(72, 31) No resource found that matches the given name (at 'layout_above' with value '@id/seconds_space').
Warning:string 'mdtp_sans_serif' has no default translation.
/myApp/app/build/intermediates/res/merged/debug/layout-land/mdtp_time_header_label.xml
Error:(72, 31) No resource found that matches the given name (at 'layout_above' with value '@id/seconds_space').
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

**Comment by meddd** [comment]
I get your sample of range picker, and in build.gradle  add:
compile 'com.wdullaer:materialdatetimepicker:3.0.0'
It is imposible to compile. Error describe above.

**Comment by RozDavid** [comment]
Hi guys, I know its a bit late, but I found a way of solving it.
Because this lib was built based on the previous version of the original daterangepicker, this might make conflicts in the gradle build. 
But using the version that borax used for his/her library will work just fine. 

Just compile this version in your gradle:
compile 'com.wdullaer:materialdatetimepicker:2.5.0'

I hope I could help

**Comment by rostgoat** [comment]
@RozDavid I just tested your solution with `'com.borax12.materialdaterangepicker:library:1.9'` and it does NOT work unfortunately.

**Comment by ghost** [comment]
Hi,i found the problem and solved it, if u use both library "material time picker" and "material date range picker" together,It doesn't work because both library xml files Have the same name.u should add materialDateRangePicker to your project as a module and refactor->rename all the xml files and rebuild and run.its working

**Comment by heysupratim** [comment]
Hi everyone. I know this has long been overdue. I just recently came back to Open source development and this issue has been fixed now in the latest release. The two projects use a different resource qualifier now therefore, the library clashes shouldn't happen anymore
